### ISSUE TITLE
批量复制按钮消失了，但是多选框还在

### ISSUE THREAD

**Issue by kanadehusband** [Zebeqo/mikanani-script#3]
批量复制按钮消失了，但是多选框还在

**Comment by kanadehusband** [comment]
![下载](https://github.com/Zebeqo/mikanani-script/assets/47624644/8ec6f49e-69d4-4039-9948-88d0737fd838)

**Comment by Zebeqo** [comment]
改了，更新一下就行，感谢提醒！
